"""The areas the picker offers, and the join between them and the venue data.

`REGIONS` in the registry is the only place a city is assigned to an area, so nothing at
runtime notices a typo or a town that has quietly lost its cinema: the client would draw
an area whose count is short, or none at all. Both directions are asserted here, and
data/regions.json is checked against the registry so an edit without a rebuild fails.
"""
import json
import unittest

import _ctx
import registry

DATA = _ctx.ROOT / "data"


def cities_with_venues():
    """-> {city: venue count} from the committed venue data, Finnkino included."""
    out = {}
    for path in DATA.glob("venues-*.json"):
        for v in json.loads(path.read_text(encoding="utf-8"))["venues"]:
            out[v["city"]] = out.get(v["city"], 0) + 1
    for a in json.loads((DATA / "areas.json").read_text(encoding="utf-8"))["areas"]:
        city = a["name"].rsplit(" ", 1)[-1]
        out[city] = out.get(city, 0) + 1
    return out


class RegionsTest(unittest.TestCase):
    def test_a_city_belongs_to_one_area(self):
        """Overlapping areas would offer the same cinema through two rows and make a
        city's area ambiguous."""
        seen = {}
        for r in registry.REGIONS:
            for c in r["cities"]:
                self.assertNotIn(c, seen, f"{c} is in {seen.get(c)} and {r['name']}")
                seen[c] = r["name"]

    def test_every_city_named_has_a_cinema(self):
        """A name that no venue file backs is a dead entry: the area's count is short and
        nothing else says so."""
        have = cities_with_venues()
        for r in registry.REGIONS:
            for c in r["cities"]:
                self.assertIn(c, have, f"{r['name']} names {c}, which has no venue")

    def test_an_area_holds_two_cinema_cities(self):
        """One city is not an area, it is that city's own combined row under a second
        name. The client drops such an area as well; this says so at the source."""
        have = cities_with_venues()
        for r in registry.REGIONS:
            live = [c for c in r["cities"] if c in have]
            self.assertGreaterEqual(len(live), 2, r["name"])

    def test_the_generated_file_matches_the_registry(self):
        """data/regions.json is generated by scripts/build_regions.py. Committed stale, the
        client draws yesterday's areas."""
        body = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
        self.assertEqual(body["regions"], registry.regions())

    def test_the_published_file_carries_only_what_the_client_reads(self):
        """`km` documents the cut for a reader of the registry. It is not published: the
        figures are estimates, and an estimate in data/ reads as measured."""
        body = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
        for r in body["regions"] + registry.regions():
            self.assertEqual(sorted(r), ["cities", "en", "name", "sv"])

    def test_every_area_is_named_in_three_languages(self):
        """An area with no translation reads out in Finnish to an English reader, and the
        search misses it entirely when the query is in their language."""
        for r in registry.REGIONS:
            for key in ("name", "sv", "en"):
                self.assertTrue(r.get(key), f"{r['name']} has no {key}")

    def test_no_two_areas_share_a_name_in_any_language(self):
        """Two areas reading the same in one language would make the picker ambiguous in
        that language only."""
        for key in ("name", "sv", "en"):
            names = [r[key] for r in registry.REGIONS]
            self.assertEqual(len(names), len(set(names)), key)


if __name__ == "__main__":
    unittest.main()
