"""The areas the picker offers, and the join between them and the venue data.

`REGIONS` in the registry is the only place a city is assigned to an area, so nothing at
runtime notices a typo or a town that has quietly lost its cinema: the client would draw
an area whose count is short, or none at all. Both directions are asserted here, and
data/regions.json is checked against the registry so an edit without a rebuild fails.

A city is backed either by committed venue data or by an adapter that names it. A
provider is registered one commit and fetched the next, so for that window its cities
are real and its `data/venues-{id}.json` does not exist. A typo and a town whose cinema
is gone appear in neither set.
"""
import importlib
import json
import unittest

import _ctx
import registry

DATA = _ctx.ROOT / "data"


def cities_with_venues():
    """-> {city: venue count} from the committed venue data, Finnkino included."""
    out = {}
    for path in DATA.glob("venues-*.json"):
        for v in json.loads(path.read_text(encoding="utf-8"))["venues"]:
            out[v["city"]] = out.get(v["city"], 0) + 1
    for a in json.loads((DATA / "areas.json").read_text(encoding="utf-8"))["areas"]:
        city = a["name"].rsplit(" ", 1)[-1]
        out[city] = out.get(city, 0) + 1
    return out


def cities_declared_by_adapters():
    """-> {city} every adapter's SITES names, run or not.

    Imported inside the function. A provider module imported at the top of a test file
    is captured before `test_common_fetch` reloads `common`, and the stale
    `EmptyProgramme` that leaves behind turns unrelated tests red.
    """
    out = set()
    for name in registry.modules():
        mod = importlib.import_module(name)
        for site in mod.SITES:
            for v in site["venues"]:
                out.add(v["city"])
    return out


def providers_declaring(city):
    """-> {provider id} whose SITES put a venue in `city`."""
    out = set()
    for name in registry.modules():
        mod = importlib.import_module(name)
        for site in mod.SITES:
            if any(v["city"] == city for v in site["venues"]):
                out.add(site["provider"])
    return out


def cities_covered():
    """Committed venue data plus the cities the adapters name."""
    return set(cities_with_venues()) | cities_declared_by_adapters()


class RegionsTest(unittest.TestCase):
    def test_a_city_belongs_to_one_area(self):
        """Overlapping areas would offer the same cinema through two rows and make a
        city's area ambiguous."""
        seen = {}
        for r in registry.REGIONS:
            for c in r["cities"]:
                self.assertNotIn(c, seen, f"{c} is in {seen.get(c)} and {r['name']}")
                seen[c] = r["name"]

    def test_every_city_named_has_a_cinema(self):
        """A name that neither the data nor an adapter backs is a dead entry: the
        area's count is short and nothing else says so."""
        have = cities_covered()
        for r in registry.REGIONS:
            for c in r["cities"]:
                self.assertIn(c, have, f"{r['name']} names {c}, which no venue "
                              f"file and no adapter backs")

    def test_a_city_the_data_lacks_belongs_to_a_provider_that_has_not_run(self):
        """Bounds the adapter half of the check above. A region city missing from the
        data has to be served by a provider with no venue file at all, so a cinema
        dropped from a provider that has one still fails. Once the run lands, the
        city is in the committed set and this passes unchanged."""
        have = cities_with_venues()
        for r in registry.REGIONS:
            for c in r["cities"]:
                if c in have:
                    continue
                for pid in providers_declaring(c):
                    with self.subTest(city=c, provider=pid):
                        self.assertFalse(
                            (DATA / f"venues-{pid}.json").exists(),
                            f"{pid} has committed venues and none of them is in {c}, "
                            f"so {r['name']} draws a city that is no longer there")

    def test_an_area_holds_two_cinema_cities(self):
        """One city is not an area, it is that city's own combined row under a second
        name. The client drops such an area as well; this says so at the source."""
        have = cities_covered()
        for r in registry.REGIONS:
            live = [c for c in r["cities"] if c in have]
            self.assertGreaterEqual(len(live), 2, r["name"])

    def test_the_generated_file_matches_the_registry(self):
        """data/regions.json is generated by scripts/build_regions.py. Committed stale, the
        client draws yesterday's areas."""
        body = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
        self.assertEqual(body["regions"], registry.regions())

    def test_the_published_file_carries_only_what_the_client_reads(self):
        """`km` documents the cut for a reader of the registry. It is not published: the
        figures are estimates, and an estimate in data/ reads as measured."""
        body = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
        for r in body["regions"] + registry.regions():
            self.assertEqual(sorted(r), ["cities", "en", "name", "sv"])

    def test_every_area_is_named_in_three_languages(self):
        """An area with no translation reads out in Finnish to an English reader, and the
        search misses it entirely when the query is in their language."""
        for r in registry.REGIONS:
            for key in ("name", "sv", "en"):
                self.assertTrue(r.get(key), f"{r['name']} has no {key}")

    def test_no_two_areas_share_a_name_in_any_language(self):
        """Two areas reading the same in one language would make the picker ambiguous in
        that language only."""
        for key in ("name", "sv", "en"):
            names = [r[key] for r in registry.REGIONS]
            self.assertEqual(len(names), len(set(names)), key)


if __name__ == "__main__":
    unittest.main()
