#!/usr/bin/env python3
"""Pre-render one indexable page per venue and per multi-venue city, in fi and en.

Why pre-render at all: the app is a single JS-rendered URL, so the whole site was one
entry in a search index no matter how much markup went in `<head>`. Structured data does
not create pages. These do, from the same committed JSON the app reads, so there is one
source of truth and no second fetcher.

    /teatteri/{slug}/           fi, one venue        /en/theatre/{slug}/
    /kaupunki/{slug}/           fi, a whole city     /en/city/{slug}/
    /sitemap.xml                every page, both languages

City pages exist only where a city has more than one venue, which is the same rule the
app uses for its combined view: five cities today (Espoo, Helsinki, Kotka, Savonlinna,
Tampere). A city page for a one-venue city would be the venue page at a second URL, and
duplicate content at two URLs is worse than one good one. Single-venue cities are covered
by putting the city in the venue page's title, h1 and JSON-LD address instead.

Deliberate constraints:

- **No third-party requests.** Inline CSS, no webfont, and only same-origin posters
  (`data/posters/...`) are rendered; a poster hot-linked from a cinema CDN is skipped
  rather than made to leak a visitor's IP on a page they arrived at from Google. See the
  Privacy section of the README.
- **A page is rewritten only when its bytes change.** Four runs a day across ~100 pages
  would otherwise commit megabytes of near-identical HTML forever. Quiet venues change
  once a week.
- **No timestamp in the page body**, for the same reason: `generated` moves every run and
  would defeat the comparison above. Freshness belongs in the app, which the page links.
- **No `aggregateRating` in the markup.** The ratings are TMDB's, and presenting another
  party's ratings as the page's own is against Google's structured-data guidelines. The
  rating is shown as text, credited, and left out of the JSON-LD.
"""
import html
import json
import re
import sys
import unicodedata
import urllib.parse
from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "providers"))

import common                                    # noqa: E402
from synmerge import norm                        # noqa: E402

ROOT = HERE.parent
DATA = ROOT / "data"
FI = ZoneInfo("Europe/Helsinki")
SITE = "https://leffavuoro.fi"
# The route a cinema uses to ask a question or to be taken out. The pipeline's
# User-Agent points every provider at this site, so these pages have to answer too --
# a search result is as likely a first landing as the app itself. Constant, so
# write_if_changed keeps working.
CONTACT = "tiles-39nomads@icloud.com"

# Posters that reached the page generator still pointing at somebody else's host. Every
# provider's images are supposed to be rewritten into data/posters/ by mirror_posters,
# which runs immediately before this. A non-zero count here means that did not happen for
# some venue, and the reader sees a placeholder tile instead of a poster -- silently,
# because the page renders fine without it.
#
# Live cause, 2026-08-30: the local half publishes Kino Engel and Kino Akseli posters as
# the cinema's own URLs and only the cloud run rewrites them, so a cancelled cloud run
# left two venues with no posters at all until the next cron. The workflow no longer
# cancels; this line is here so the next way it happens is not silent too.
_unmirrored_hosts = {}


def _unmirrored(img):
    if img.startswith("http") or img.startswith("//"):
        host = img.split("/")[2] if "//" in img else img
        _unmirrored_hosts[host] = _unmirrored_hosts.get(host, 0) + 1
    return ""
DAYS = 4          # today plus three: enough to answer "what is on", small enough to commit
CITY_DAYS = 2     # a ten-venue city at seven days was a 1.2 MB page
LD_DAYS = 2       # markup for today and tomorrow only, see ld_json()


# ---------------------------------------------------------------- strings

# Finnish city names inflect irregularly: Helsinki -> Helsingissä, Tampere -> Tampereella,
# Espoo -> Espoossa. Suffixing a case ending onto the nominative produces "Helsinkissä",
# which is exactly the tell that a page was generated by a script. Every string below
# therefore uses the city name in the nominative with a separator, which stays correct for
# any city a future provider brings.
L = {
    "fi": {
        "lang": "fi", "locale": "fi_FI",
        "venue_title": "{venue}, {city} – elokuvat ja näytösajat",
        "city_title": "Elokuvat ja näytösajat – {city}",
        "venue_h1": "{venue} – näytösajat",
        "city_h1": "Elokuvat ja näytösajat – {city}",
        "venue_desc": "{venue} ({city}): elokuvat, kellonajat, ikärajat ja liput "
                      "lähipäiville.",
        "city_desc": "Kaikki elokuvateatterit ja näytösajat – {city}: {venues}.",
        "venue_intro": "Näytösajat lähipäiville. Kellonaika vie suoraan lippusivulle "
                       "({provider}). Koko ohjelmisto ja suodattimet sovelluksessa.",
        "city_intro": "Näytösajat {n} teatterista: {venues}.",
        "app": "Ajantasaiset ajat, suodattimet ja koko ohjelmisto: Leffavuoro",
        "today": "tänään", "tomorrow": "huomenna",
        "no_shows": "Ei julkaistuja näytöksiä lähipäiville.",
        "mins": "min", "rating_src": "arvosana TMDB",
        "other_venues": "Muut teatterit samassa kaupungissa",
        "city_link": "Kaikki teatterit – {city}",
        "days": ["ma", "ti", "ke", "to", "pe", "la", "su"],
        "sources": "Näytöstiedot: kyseisen teatterin oma ohjelmisto. Arvosanat ja "
                   "kuvaukset: TMDB. Henkilökohtainen harrastusprojekti, ei "
                   "sidoksissa teattereihin.",
        "contact": "Elokuvateattereille: yhteydenotot ja poistopyynnöt",
    },
    "en": {
        "lang": "en", "locale": "en_GB",
        "venue_title": "{venue}, {city} – films and showtimes",
        "city_title": "Films and showtimes – {city}",
        "venue_h1": "{venue} – showtimes",
        "city_h1": "Films and showtimes – {city}",
        "venue_desc": "{venue} ({city}): films, times, age limits and tickets for the "
                      "next few days.",
        "city_desc": "Every cinema and showtime in one list – {city}: {venues}.",
        "venue_intro": "Showtimes for the next few days. A time goes straight to the "
                       "ticket page ({provider}). Full schedule and filters in the app.",
        "city_intro": "Showtimes from {n} cinemas: {venues}.",
        "app": "Live times, filters and the full schedule: Leffavuoro",
        "today": "today", "tomorrow": "tomorrow",
        "no_shows": "No showtimes published for the next few days.",
        "mins": "min", "rating_src": "rating by TMDB",
        "other_venues": "Other cinemas in the same city",
        "city_link": "All cinemas – {city}",
        "days": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        "sources": "Showtimes: each cinema's own schedule. Ratings and descriptions: "
                   "TMDB. A personal hobby project, unaffiliated with the cinemas.",
        "contact": "For cinemas: enquiries and removal requests",
    },
}

CSS = """
:root{--bg:#F6F7F9;--surface:#fff;--ink:#16181D;--muted:#5C6470;--line:#E3E6EB;
--accent:#8A6508}
@media(prefers-color-scheme:dark){:root{--bg:#0D0E12;--surface:#16181F;--ink:#EDEDEA;
--muted:#8B93A1;--line:#262A33;--accent:#E8B84B}}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--ink);font:16px/1.5 system-ui,-apple-system,
"Segoe UI",Roboto,sans-serif;padding:1.25rem;max-width:52rem;margin:0 auto}
a{color:var(--accent)}
h1{font-size:1.5rem;line-height:1.2;margin-bottom:.4rem}
h2{font-size:1.05rem;margin:1.75rem 0 .6rem;padding-bottom:.3rem;
border-bottom:1px solid var(--line)}
h3{font-size:1rem;margin:0 0 .2rem}
p{color:var(--muted);margin-bottom:.75rem}
.app{display:inline-block;margin:.5rem 0 1rem;padding:.5rem .9rem;background:var(--surface);
border:1px solid var(--line);border-radius:999px;text-decoration:none}
.film{background:var(--surface);border:1px solid var(--line);border-radius:.6rem;
padding:.8rem;margin-bottom:.6rem;display:flex;gap:.8rem}
.film img{width:56px;height:84px;object-fit:cover;border-radius:.3rem;flex:0 0 auto}
.meta{color:var(--muted);font-size:.85rem;margin-bottom:.45rem}
.times{list-style:none;display:flex;flex-wrap:wrap;gap:.35rem}
.times a{display:inline-block;padding:.25rem .55rem;border:1px solid var(--line);
border-radius:.35rem;background:var(--bg);text-decoration:none;font-size:.9rem}
.syn{font-size:.9rem;color:var(--muted);margin:.35rem 0 .5rem}
nav.also{margin-top:2rem;font-size:.9rem}
nav.also ul{list-style:none;display:flex;flex-wrap:wrap;gap:.5rem}
footer{margin-top:2.5rem;padding-top:1rem;border-top:1px solid var(--line);
color:var(--muted);font-size:.85rem}
footer a{color:inherit}
""".strip()


# ---------------------------------------------------------------- helpers

def slug(s):
    """URL slug. ä/ö/å are folded by hand first: NFKD does not decompose them in all
    Python builds, and a venue silently losing a letter changes its URL."""
    s = (s or "").lower()
    for a, b in (("ä", "a"), ("ö", "o"), ("å", "a"), ("é", "e"), ("ü", "u")):
        s = s.replace(a, b)
    s = "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


def esc(s):
    return html.escape(str(s or ""), quote=True)


def city_of(v):
    """Mirror of cityOf() in index.html: BioRex and friends ship `city`, Finnkino names
    carry it as the last word ("Plevna Tampere")."""
    if v.get("city"):
        return v["city"]
    w = (v.get("name") or "").strip().split()
    return w[-1] if len(w) > 1 else (v.get("name") or "")


def short_of(v):
    if v.get("short"):
        return v["short"]
    city, n = city_of(v), (v.get("name") or "").strip()
    return n[:-(len(city) + 1)].strip() if n.endswith(" " + city) else n


def label_of(v, chains):
    chain, short = chains.get(v["provider"], ""), short_of(v)
    return f"{chain} {short}" if chain and not short.startswith(chain) else short


def load_venues():
    out = []
    areas = json.loads((DATA / "areas.json").read_text())
    for a in areas.get("areas", []):
        out.append({**a, "provider": "finnkino"})
    for f in sorted(DATA.glob("venues-*.json")):
        d = json.loads(f.read_text())
        for v in d.get("venues", []):
            out.append({**v, "provider": d["provider"]})
    return out


def load_shows(vid):
    p = DATA / f"area-{vid}.json"
    if not p.exists():
        return []
    return json.loads(p.read_text()).get("shows", [])


def duration(minutes):
    try:
        n = int(minutes)
    except (TypeError, ValueError):
        return None
    return f"PT{n}M" if n > 0 else None


def genre_names(gids, genres, gmap, lang):
    """TMDB ids where we have them, the provider's own string otherwise. The chains
    disagree on spelling and their strings are Finnish even in English mode, so ids win
    when both exist."""
    if gids:
        names = [gmap.get(lang, {}).get(str(g)) for g in gids]
        names = [n for n in names if n]
        if names:
            return ", ".join(names)
    return (genres or "").strip().strip(",")


# ---------------------------------------------------------------- rendering

def group_by_day(shows, today, days=DAYS):
    """{iso date: {film title: [show, ...]}} for the next `days` days, times ascending."""
    window = {(today + timedelta(days=i)).isoformat() for i in range(days)}
    days = {}
    for s in sorted(shows, key=lambda x: x.get("start") or ""):
        start = s.get("start") or ""
        d = start[:10]
        if d not in window:
            continue
        days.setdefault(d, {}).setdefault(s.get("title") or "?", []).append(s)
    return days


def day_label(iso, today, t):
    d = date.fromisoformat(iso)
    if d == today:
        head = t["today"]
    elif d == today + timedelta(days=1):
        head = t["tomorrow"]
    else:
        head = t["days"][d.weekday()]
    return f"{head} {d.day}.{d.month}."


def clip(text, n=200):
    """Truncate on a word boundary with an ellipsis. Cutting mid-word looked like a bug
    and Google will re-truncate the snippet anyway."""
    text = " ".join((text or "").split())
    if len(text) <= n:
        return text
    cut = text[:n]
    sp = cut.rfind(" ")
    return (cut[:sp] if sp > n * 0.6 else cut).rstrip(" ,.;:") + "\u2026"


def film_block(title, shows, extra, gmap, lang, t, with_venue, syn_seen):
    s0 = shows[0]
    bits = []
    if s0.get("len"):
        bits.append(f"{esc(s0['len'])} {t['mins']}")
    if s0.get("rating"):
        bits.append(esc(s0["rating"]))
    g = genre_names(s0.get("gids"), s0.get("genres"), gmap, lang)
    if g:
        bits.append(esc(g))
    if s0.get("tmdb"):
        bits.append(f"{s0['tmdb']:.1f}/10 ({t['rating_src']})")

    # A synopsis only on a film's first appearance: a four-day page repeats the same
    # title daily, and printing it each time both bloated the page and read like padding.
    fx = extra.get(norm(title)) or {}
    syn = ""
    if title not in syn_seen:
        syn = clip(((fx.get("s") or {}).get(lang) or ""))
        syn_seen.add(title)
    # Only same-origin posters: a hot-linked CDN poster would leak the visitor's IP.
    img = s0.get("img") or ""
    poster = f'<img src="/{esc(img)}" alt="" width="56" height="84" loading="lazy">' \
        if img.startswith("data/posters/") else _unmirrored(img)

    times = []
    for s in shows:
        clock = (s.get("start") or "")[11:16]
        bit = clock
        if with_venue and s.get("venueShort"):
            bit += f" {esc(s['venueShort'])}"
        elif s.get("aud"):
            bit += f" {esc(s['aud'])}"
        if s.get("lang"):
            bit += f" {esc(s['lang'])}"
        url = s.get("url") or ""
        times.append(f'<li><a href="{esc(url)}" rel="nofollow noopener">{bit}</a></li>'
                     if url.startswith("http") else f"<li>{bit}</li>")

    return (f'<article class="film">{poster}<div>'
            f"<h3>{esc(title)}</h3>"
            f'<div class="meta">{" · ".join(bits)}</div>'
            + (f'<p class="syn">{esc(syn)}</p>' if syn else "")
            + f'<ul class="times">{"".join(times)}</ul>'
            "</div></article>")


def poster_url(s, extra):
    """Absolute poster URL for markup, or None.

    A URL in JSON-LD is read by the crawler, not fetched by the visitor's browser, so a
    cinema CDN or image.tmdb.org address here does not leak a reader's IP the way an
    <img> would. That is why markup can use posters the page itself refuses to render.
    """
    img = (s.get("img") or "").strip()
    if img.startswith("data/posters/"):
        return f"{SITE}/{img}"
    if img.startswith("http"):
        return img
    fx = extra.get(norm(s.get("title") or "")) or {}
    return fx.get("img") or None


def ld_json(days, today, city, extra):
    """ScreeningEvent per showtime, for today and tomorrow only.

    Three deliberate economies, all of which came out of a 1.2 MB Helsinki page:

    - **Only LD_DAYS of events.** Rich results are a near-term surface, and a crawler
      that revisits weekly would be reading stale markup for day six anyway.
    - **Theatres are `@id` nodes referenced by each event** rather than a nested address
      repeated per showtime. On a ten-venue city page that was most of the payload.
    - **No `availability`.** Sold-out state flips several times a day, so it would
      guarantee a rewrite of every popular page on every run while being stale in the
      index regardless. Price is stable enough to keep.

    No `aggregateRating`: the ratings are TMDB's, and presenting another party's ratings
    as the page's own is against Google's structured-data guidelines.
    """
    window = {(today + timedelta(days=i)).isoformat() for i in range(LD_DAYS)}
    theatres, events = {}, []
    for iso in sorted(d for d in days if d in window):
        for title, shows in days[iso].items():
            for s in shows:
                theatre = s.get("theatre") or ""
                tid = f"#venue-{slug(theatre)}"
                if tid not in theatres:
                    theatres[tid] = {
                        "@type": "MovieTheater", "@id": tid, "name": theatre,
                        "address": {"@type": "PostalAddress",
                                    "addressLocality": city, "addressCountry": "FI"},
                    }
                ev = {
                    "@type": "ScreeningEvent",
                    "name": title,
                    "startDate": s.get("start"),
                    "location": {"@id": tid},
                }
                # Google validates a nested Movie against its own Movie requirements, and
                # `image` is the one it treats as critical: without it the item is parsed,
                # rejected and reported as invalid. A Movie with no poster is no use to it
                # anyway, so the event keeps its name and drops the nested work rather
                # than shipping something that will only ever fail. One showtime in 3509
                # has no poster from any source.
                poster = poster_url(s, extra)
                if poster:
                    work = {"@type": "Movie", "name": title, "image": poster}
                    dur = duration(s.get("len"))
                    if dur:
                        work["duration"] = dur
                    if s.get("tmdbId"):
                        work["sameAs"] = \
                            f"https://www.themoviedb.org/movie/{s['tmdbId']}"
                    ev["workPresented"] = work
                if s.get("url", "").startswith("http"):
                    ev["url"] = s["url"]
                    if s.get("price"):
                        m = re.search(r"\d+([.,]\d+)?", str(s["price"]))
                        if m:
                            ev["offers"] = {"@type": "Offer", "url": s["url"],
                                            "price": m.group(0).replace(",", "."),
                                            "priceCurrency": "EUR"}
                events.append(ev)
    out = json.dumps({"@context": "https://schema.org",
                      "@graph": list(theatres.values()) + events},
                     ensure_ascii=False, separators=(",", ":"))
    # This string is embedded inside <script>, and the HTML parser ends a script
    # element at the first literal "</script>" regardless of its type attribute --
    # valid JSON is not enough here. Titles, venue names and URLs are provider text,
    # so a hostile or merely unlucky title could otherwise close the element and open
    # a live script context. \uXXXX escapes are equivalent JSON, so a consumer parses
    # the identical value. U+2028/U+2029 are legal in JSON but not in JS source, and
    # ensure_ascii=False would emit them raw.
    for ch, rep in (("&", "\\u0026"), ("<", "\\u003c"), (">", "\\u003e"),
                    ("\u2028", "\\u2028"), ("\u2029", "\\u2029")):
        out = out.replace(ch, rep)
    return out


def page(*, lang, path_fi, path_en, title, desc, h1, intro, days, today, t,
         extra, gmap, city, also, og_image, app_href):
    other = path_en if lang == "fi" else path_fi
    body, syn_seen = [], set()
    if not days:
        body.append(f"<p>{esc(t['no_shows'])}</p>")
    for iso in sorted(days):
        body.append(f"<h2>{esc(day_label(iso, today, t))}</h2>")
        for title_, shows in sorted(days[iso].items(),
                                    key=lambda kv: (kv[1][0].get("start") or "", kv[0])):
            body.append(film_block(title_, shows, extra, gmap, lang, t,
                                   with_venue=bool(also.get("multi")),
                                   syn_seen=syn_seen))
    nav = ""
    if also.get("links"):
        items = "".join(f'<li><a href="{esc(u)}">{esc(n)}</a></li>'
                        for n, u in also["links"])
        nav = (f'<nav class="also"><h2>{esc(also["heading"])}</h2>'
               f"<ul>{items}</ul></nav>")
    self_path = path_fi if lang == "fi" else path_en
    return f"""<!DOCTYPE html>
<html lang="{t['lang']}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{SITE}{self_path}">
<link rel="alternate" hreflang="fi" href="{SITE}{path_fi}">
<link rel="alternate" hreflang="en" href="{SITE}{path_en}">
<link rel="alternate" hreflang="x-default" href="{SITE}{path_fi}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Leffavuoro">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{SITE}{self_path}">
<meta property="og:image" content="{SITE}{og_image}">
<meta property="og:locale" content="{t['locale']}">
<link rel="icon" href="/icon-192.png">
<style>{CSS}</style>
<script type="application/ld+json">{ld_json(days, today, city, extra)}</script>
</head>
<body>
<h1>{esc(h1)}</h1>
<p>{esc(intro)}</p>
<a class="app" href="{esc(app_href)}">{esc(t['app'])}</a>
{''.join(body)}
{nav}
<p style="margin-top:1.5rem"><a href="{esc(other)}">{'In English' if lang == 'fi' else 'Suomeksi'}</a></p>
<footer>{esc(t['sources'])}<br>{esc(t['contact'])} · <a href="mailto:{CONTACT}">{CONTACT}</a></footer>
</body>
</html>
"""


# ---------------------------------------------------------------- main

# Venue slugs that were public before a naming fix, and the venue id each now belongs to.
#
# A slug is built from the chain label and the city, so correcting a label moves the URL.
# Studio 123's two venues rendered their name twice ("Studio 123 Kouvola Studio 123")
# until 2026-08-30, and the fix silently retired four indexed paths -- bookmarks, links
# and anything Google had already crawled would 404. The pages are regenerated as
# redirects instead of being deleted.
#
# Deliberately a fixed table rather than a general aliasing framework: it is four entries
# for one mistake, and a mechanism that rewrites URLs on every label edit would make it
# easy to keep moving them. Add here only when a live URL has actually changed.
LEGACY_VENUE_SLUGS = {
    "studio-123-jarvenpaa-studio-123-jarvenpaa": "s3-jarvenpaa",
    "studio-123-kouvola-studio-123-kouvola": "s3-kouvola",
}


def redirect_page(lang, to_path, label):
    """A minimal page that sends a reader to the URL this one became.

    Not a copy of the venue page: duplicating the content under both URLs is what
    `canonical` exists to prevent, and the schedule would then age in two places. The
    meta refresh moves a browser, the canonical and `noindex` tell a crawler which URL is
    real, and the anchor is what someone lands on if neither runs. `follow` rather than
    `nofollow`, so the link is what carries the old URL's standing to the new one.

    Nothing volatile in it, so `write_if_changed` keeps returning "kept" and these four
    files stop appearing in diffs.
    """
    t = ("Sivu on siirtynyt" if lang == "fi" else "This page has moved")
    go = ("Siirry teatterin sivulle" if lang == "fi" else "Go to the cinema's page")
    return (f'<!doctype html>\n<html lang="{lang}">\n<head>\n<meta charset="utf-8">\n'
            f'<meta name="viewport" content="width=device-width,initial-scale=1">\n'
            f'<title>{esc(t)}: {esc(label)}</title>\n'
            f'<link rel="canonical" href="{SITE}{to_path}">\n'
            f'<meta name="robots" content="noindex,follow">\n'
            f'<meta http-equiv="refresh" content="0;url={to_path}">\n'
            f'</head>\n<body>\n'
            f'<h1>{esc(t)}</h1>\n'
            f'<p><a href="{to_path}">{esc(go)}: {esc(label)}</a></p>\n'
            f'</body>\n</html>\n')


def write_if_changed(path, text, stats):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        stats["kept"] += 1
        return
    common.write_text_atomic(path, text)
    stats["written"] += 1


def main() -> int:
    providers = {p["id"]: p for p in
                 json.loads((DATA / "providers.json").read_text())["providers"]}
    chains = {k: v.get("label", k) for k, v in providers.items()}
    gmap = json.loads((DATA / "tmdb-genres.json").read_text())
    extra = json.loads((DATA / "films-extra.json").read_text()).get("films", {})
    today = datetime.now(FI).date()

    venues = load_venues()
    for v in venues:
        v["city"] = city_of(v)
        v["label"] = label_of(v, chains)
        v["slug"] = slug(f"{v['label']} {v['city']}")

    seen = {}
    for v in venues:                     # a collision would silently drop a venue's page
        if v["slug"] in seen:
            v["slug"] = f"{v['slug']}-{slug(v['id'])}"
        seen[v["slug"]] = v["id"]

    by_city = {}
    for v in venues:
        by_city.setdefault(v["city"], []).append(v)
    multi = {c: vs for c, vs in by_city.items() if len(vs) > 1}

    stats = {"written": 0, "kept": 0}
    urls = []

    def paths_venue(v):
        return f"/teatteri/{v['slug']}/", f"/en/theatre/{v['slug']}/"

    def paths_city(c):
        s = slug(c)
        return f"/kaupunki/{s}/", f"/en/city/{s}/"

    # ---- venue pages
    for v in venues:
        shows = load_shows(v["id"])
        days = group_by_day(shows, today)
        p_fi, p_en = paths_venue(v)
        first_poster = next((s["img"] for iso in sorted(days)
                             for sh in days[iso].values() for s in sh
                             if (s.get("img") or "").startswith("data/posters/")), None)
        og = f"/{first_poster}" if first_poster else "/icon-512.png"
        links, heading = [], ""
        if v["city"] in multi:
            cf, ce = paths_city(v["city"])
            links = [(L["fi"]["city_link"].format(city=v["city"]), cf)]
            heading = L["fi"]["other_venues"]
        for lang in ("fi", "en"):
            t = L[lang]
            cf, ce = (paths_city(v["city"]) if v["city"] in multi else ("", ""))
            lk = [(t["city_link"].format(city=v["city"]), cf if lang == "fi" else ce)] \
                if v["city"] in multi else []
            text = page(
                lang=lang, path_fi=p_fi, path_en=p_en,
                title=t["venue_title"].format(venue=v["label"], city=v["city"]),
                desc=t["venue_desc"].format(venue=v["label"], city=v["city"]),
                h1=t["venue_h1"].format(venue=v["label"]),
                intro=t["venue_intro"].format(provider=chains.get(v["provider"], "")),
                days=days, today=today, t=t, extra=extra, gmap=gmap, city=v["city"],
                also={"links": lk,
                      "heading": t["other_venues"],
                      "multi": False},
                og_image=og,
                # Deep link, so a reader arriving from search opens on this venue instead
                # of whatever the app last had selected.
                app_href="/?area=" + urllib.parse.quote(v["id"]))
            out = ROOT / (p_fi if lang == "fi" else p_en).strip("/") / "index.html"
            write_if_changed(out, text, stats)
        urls += [p_fi, p_en]

    # ---- redirects for venue URLs that were public under an older slug. Written after
    # the venue pages so the destination exists, and deliberately not added to `urls`:
    # the sitemap advertises canonical URLs only.
    by_id = {v["id"]: v for v in venues}
    for old_slug, vid in LEGACY_VENUE_SLUGS.items():
        v = by_id.get(vid)
        if v is None or v["slug"] == old_slug:
            continue          # venue gone, or the slug is current again -- nothing to do
        for lang, prefix, dest in (("fi", "teatteri", paths_venue(v)[0]),
                                   ("en", "en/theatre", paths_venue(v)[1])):
            out = ROOT / prefix / old_slug / "index.html"
            write_if_changed(out, redirect_page(lang, dest, v["label"]), stats)

    # ---- city pages, only where the app offers a combined view
    for c, vs in multi.items():
        merged = []
        for v in vs:
            for s in load_shows(v["id"]):
                merged.append({**s, "venueShort": short_of(v)})
        days = group_by_day(merged, today, CITY_DAYS)
        p_fi, p_en = paths_city(c)
        names = ", ".join(sorted(v["label"] for v in vs))
        first_poster = next((s["img"] for iso in sorted(days)
                             for sh in days[iso].values() for s in sh
                             if (s.get("img") or "").startswith("data/posters/")), None)
        og = f"/{first_poster}" if first_poster else "/icon-512.png"
        for lang in ("fi", "en"):
            t = L[lang]
            lk = [(v["label"], paths_venue(v)[0 if lang == "fi" else 1]) for v in
                  sorted(vs, key=lambda x: x["label"])]
            text = page(
                lang=lang, path_fi=p_fi, path_en=p_en,
                title=t["city_title"].format(city=c),
                desc=t["city_desc"].format(city=c, venues=names),
                h1=t["city_h1"].format(city=c),
                intro=t["city_intro"].format(n=len(vs), city=c, venues=names),
                days=days, today=today, t=t, extra=extra, gmap=gmap, city=c,
                also={"links": lk,
                      "heading": t["other_venues"],
                      "multi": True},
                og_image=og,
                app_href="/?area=" + urllib.parse.quote("city:" + c))
            out = ROOT / (p_fi if lang == "fi" else p_en).strip("/") / "index.html"
            write_if_changed(out, text, stats)
        urls += [p_fi, p_en]

    # ---- sitemap
    lastmod = today.isoformat()
    entries = "\n".join(
        f"  <url><loc>{SITE}{u}</loc><lastmod>{lastmod}</lastmod></url>"
        for u in ["/"] + sorted(urls))
    sm = ('<?xml version="1.0" encoding="UTF-8"?>\n'
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
          f"{entries}\n</urlset>\n")
    write_if_changed(ROOT / "sitemap.xml", sm, stats)

    print(f"[pages] {len(venues)} venues, {len(multi)} multi-venue cities "
          f"({', '.join(sorted(multi))})")
    if _unmirrored_hosts:
        total = sum(_unmirrored_hosts.values())
        where = ", ".join(f"{h} x{n}" for h, n in sorted(_unmirrored_hosts.items()))
        print(f"[pages] WARNING: {total} poster references were still remote and were "
              f"dropped from the markup, so those films render a placeholder tile: "
              f"{where}. mirror_posters should have rewritten these; check whether the "
              f"cloud run before this one completed.")

    print(f"[pages] {len(urls) + 1} urls in sitemap, "
          f"{stats['written']} files written, {stats['kept']} unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
